apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mantra-dukong-1-applications

resources:
  - resources/host_mapping.yaml
  - resources/pod_disruption_budget.yaml
  - resources/authproxy.yaml

configMapGenerator:
  - envs:
      - resources/backend-configmap.yaml
    name: backend-env-variables
  - envs:
      - resources/frontend-configmap.yaml
    name: frontend-env-variables

# enable logging in logs explorer
labels:
  - pairs:
      gke.logging.enabled: "true"
    includeSelectors: false
    includeTemplates: true

helmCharts:
#
# BLOCKSCOUT STACK
#
- name: blockscout-stack
  repo: https://blockscout.github.io/helm-charts
  version: 3.0.0
  releaseName: blockscout-stack
  valuesInline:
    config:
      network:
        id: 7888
        name: om
        shortname: om
        currency:
          name: om
          symbol: OM
          decimals: 6
      prometheus:
        enabled: false
    blockscout:
      replicaCount: 2
      envFrom:
        - configMapRef:
            name: backend-env-variables
    frontend:
       envFrom:
        - configMapRef:
            name: frontend-env-variables 