{{- if .Values.customConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.customConfigMap.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
{{- with .Values.customConfigMap.data }}
    {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}