{{- $tag := (.Values.deployment.image).tag }}
{{- if and (.Values.goDBMigration.enabled) ($tag) }}
{{- $job := .Values.goDBMigration.job }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.fullname" . }}-db-migration
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    {{- include "app.selectorLabels" . | nindent 6 }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        db-migration: "true"
      annotations:
      {{- with .Values.goDBMigration.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with $job.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {}
      restartPolicy: Never
      containers:
        - name: migrate
          image: registry.tech.hextech.io/migrate/migrate:v4.15.1
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - migrate -source=gitlab://${GITLAB_TOKEN_USERNAME}:${GITLAB_TOKEN_PASSWORD}@{{ $job.git.path }}#{{ $tag }} -database=${DB_URL}/${DATABASE}?sslmode=${PGSSLMODE}\&search_path=${SCHEMA} up
          env:
            - name: DB_URL
              value: {{ $job.env.DB_URL }}
            - name: PGSSLMODE
              value: {{ $job.env.PGSSLMODE }}
            - name: DATABASE
              value: {{ $job.env.DATABASE }}
            - name: SCHEMA
              value: {{ $job.env.SCHEMA }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.fullname" . }}-db-migration
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.fullname" . }}-db-migration
                  key: password
            - name: GITLAB_TOKEN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.fullname" . }}-db-migration
                  key: gitlab_token_password
            - name: GITLAB_TOKEN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.fullname" . }}-db-migration
                  key: gitlab_token_username
{{- end }}