{{- if and .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}-{{ .Values.externalSecret.suffix }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore }}
    kind: {{ .Values.externalSecret.kind | default "ClusterSecretStore" }}
  target:
    name: {{ include "app.fullname" . }}-secret
    creationPolicy: {{ .Values.externalSecret.creationPolicy | default "Owner"}}
  data:
  {{- with .Values.externalSecret.secrets }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}