{{- if .Values.pdb }}
  {{- if or (and .Values.pdb.enabled (gt .Values.deployment.replicaCount 1.0)) (and .Values.pdb.enabled .Values.autoscaling.enabled (gt .Values.autoscaling.minReplicas 1.0)) -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  {{- if and .Values.pdb.minAvailable .Values.pdb.maxUnavailable }}
  {{ fail "Both minAvailable and maxUnavailable cannot be specified simultaneously in values.yaml" }}
  {{- else if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- else if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  {{- end }}
  {{- end }}
