{{- if .Values.volumes.enabled }}
{{- range $volume := .Values.volumes.pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $volume.name }}
spec:
  storageClassName: {{ $volume.className }}
  volumeMode: {{ $volume.volumeMode }}
  resources:
    requests:
      storage: {{ $volume.storage }}
  accessModes: {{ $volume.accessModes }}
{{- end }}
{{- end }}