apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mantra-canary-net-1-applications

resources:
  - resources/host_mapping.yaml
  - resources/pod_disruption_budget.yaml
  - secrets/secret.yaml

configMapGenerator:
  - envs:
      - resources/configmap.yaml
    name: faucet-omstead-5887-env-variables

# enable logging in logs explorer
labels:
  - pairs:
      gke.logging.enabled: "true"
    includeSelectors: false
    includeTemplates: true

helmCharts:
#
# FAUCET OMSTEAD
#
- name: generic-helm-chart
  repo: https://mantra-chain.github.io/generic-helm-chart
  version: 0.4.3
  releaseName: faucet-omstead-5887
  valuesInline:
    nameOverride: faucet-omstead-5887
    fullnameOverride: faucet-omstead-5887
    service:
      port:
        - port: 8000
          targetPort: 8000
          protocol: TCP
          name: http
    deployment:
      replicaCount: 2
      image:
        repository: ghcr.io/mantra-finance/cosmos-sdk-faucet
        pullPolicy: Always
        tag: "devops-k8s"
      annotations:
        argocd.argoproj.io/sync-wave: "2"
      service:
        port:
          - containerPort: 8000
            protocol: TCP
            name: http
      
      volumeMounts:
      - name: faucet-omstead-5887-config
        mountPath: /app/config/config.js
        subPath: config.js
      
      volumes:
      - name: faucet-omstead-5887-config
        secret:
          secretName: faucet-omstead-5887-secrets
          defaultMode: 420

    envFrom:
      - name: faucet-omstead-5887-env-variables
        type: configmap