apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mantra-dukong-1-applications

resources:
  - resources/host_mapping.yaml
  - resources/pod_disruption_budget.yaml
  - secrets/secret.yaml

configMapGenerator:
  - envs:
      - resources/configmap.yaml
    name: faucet-omstead-7888-env-variables

# enable logging in logs explorer
labels:
  - pairs:
      gke.logging.enabled: "true"
    includeSelectors: false
    includeTemplates: true

helmCharts:
#
# FAUCET OMSTEAD
#
- name: generic-helm-chart
  repo: https://mantra-chain.github.io/generic-helm-chart
  version: 0.4.3
  releaseName: faucet-omstead-7888
  valuesInline:
    nameOverride: faucet-omstead-7888
    fullnameOverride: faucet-omstead-7888
    service:
      enabled: true
      port:
        - port: 80
          targetPort: 8000
          protocol: TCP
          name: http
    deployment:
      replicaCount: 2
      image:
        repository: ghcr.io/mantra-finance/cosmos-sdk-faucet
        pullPolicy: Always
        tag: "03f46d9"
      imagePullSecrets:
        - name: ghcr-mantra-chain-applications-registry-read-secret
      annotations:
        argocd.argoproj.io/sync-wave: "2"
      service:
        port:
          - containerPort: 8000
            protocol: TCP
            name: http
      
      volumeMounts:
      - name: faucet-omstead-7888-config
        mountPath: /app/config/config.js
        subPath: config.js
      
      volumes:
      - name: faucet-omstead-7888-config
        secret:
          secretName: faucet-omstead-7888-secrets
          defaultMode: 420

      envFrom:
        - name: faucet-omstead-7888-env-variables
          type: configmap

      nodeSelector:
        cloud.google.com/gke-spot: "true"