apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: faucet.dukong.mantrachain.io
  annotations:
    external-dns.ambassador-service: emissary-ingress.emissary
spec:
  hostname: faucet.dukong.mantrachain.io
  acmeProvider:
    authority: none
  tlsSecret:
    name: dukong.asia-east2-std.testnet.mantrachain.io-wildcard-tls-secret
    namespace: emissary
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: faucet.dukong.mantrachain.io
spec:
  hostname: "faucet.dukong.mantrachain.io"
  prefix: /
  service: faucet-dukong:80
