apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mantra-dukong-1-applications

resources:
  - resources/host_mapping.yaml
  - resources/pod_disruption_budget.yaml
  - resources/authproxy.yaml

configMapGenerator:
  - envs:
      - resources/faucet-configmap.yaml
    name: faucet-env-variables

# enable logging in logs explorer
labels:
  - pairs:
      gke.logging.enabled: "true"
    includeSelectors: false
    includeTemplates: true

helmCharts:
#
# FAUCET SERVER STACK
#
- name: generic-helm-chart
  repo: https://aaronforce1.github.io/generic-helm-chart
  version: 0.4.2
  releaseName: faucet-omstead-io
  valuesFile: './values.yaml'
  valuesInline:
    nameOverride: faucet-omstead-io
    fullnameOverride: faucet-omstead-io
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: mantra-chain-mainnet-sql-op@mantra-chain-mainnet.iam.gserviceaccount.com
    service:
      port:
        - port: 8000
          targetPort: 8000
          protocol: TCP
          name: http
    deployment:
      image:
        repository: ghcr.io/mantra-chain/resolute-server
        pullPolicy: Always
        tag: "latest"
      annotations:
        argocd.argoproj.io/sync-wave: "2"
      service:
        port:
          - containerPort: 1323
            protocol: TCP
            name: http
      
      volumeMounts:
      - name: resolute-server-mainnet-secrets
        mountPath: /app/config.yaml
        subPath: config.yaml
      - name: resolute-server-mainnet-config
        mountPath: /app/networks.json
        subPath: networks.json
      
      volumes:
      - name: resolute-server-mainnet-config
        configMap:
          name: resolute-server-mainnet-config
          defaultMode: 420
      - name: resolute-server-mainnet-secrets
        secret:
          secretName: mantra-chain-mainnet-application-resolute-secrets
          defaultMode: 420
      - name: resolute-server-update-schema
        configMap:
          name: resolute-server-update-schema
          defaultMode: 420

    ingress:
      - enabled: false
        name: api
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$2
          nginx.ingress.kubernetes.io/use-regex: 'true'
        hosts:
          - host: resolute.int.mantrachain.io
            http:
              paths:
                - backend:
                    service:
                      name: resolute-server-mainnet
                      port:
                        number: 8000
                  path: /api(/|$)(.*)
                  pathType: Prefix
        tls:
          - hosts:
              - resolute.int.mantrachain.io
            secretName: int.asia-east2-std.mantrachain.io-wildcard-tls
#
# Higher Environments: Database should run as cloud-managed service
#
########################################################
## POSTGRES
########################################################
- name: postgresql
  repo: https://charts.bitnami.com/bitnami
  version: 16.0.1
  releaseName: postgresql
  namespace: mantra-mainnet-1-applications
  valuesInline:
    commonAnnotations:
      argocd.argoproj.io/sync-wave: "-1"

    global:
      postgresql:
        auth:
          database: resolute-mainnet
          username: resolute-mainnet
          existingSecret: mantra-chain-mainnet-application-resolute-secrets
          secretKeys:
            adminPasswordKey: "adminPassword"
            userPasswordKey: "userPassword"
            replicationPasswordKey: "replicationPassword"

    primary:
      initdb:
        scriptsConfigMap: postgresql-init-script
      configuration: |-
        max_connections = 500
        shared_buffers = 500MB
        listen_addresses = '*'