apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: faucet-canary-net-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        key: faucet-canary-net-secrets
      secretKey: "config.js"
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secrets-manager
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: faucet-canary-net-secrets

